appartements/urls.py
from django.urls import path
from . import views

app_name = 'appartements'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('login/', views.FormView.as_view(), name='login'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('appartements/', include('appartements.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

appartements/models.py
from django.db import models

# I better be adding the Immoweb ID to the model as well as some appartements are uploaded 
# multiple times on the website

#https://docs.djangoproject.com/fr/3.1/ref/models/fields/#enumeration-types

#change the ID system
#better add some letters before the ImmoID numbers. Letters refering to the site they were taken from.
#ex: IM9898153 for an ImmoWeb ID and ZM9898153 for a zimmoWeb
class Appartement(models.Model):
    LOW = 300
    LOW_TO_MID = 450
    MID = 600
    MID_TO_HIGH = 900
    HIGH_TO_VHIGH = 1400
    HIGH = 1800
    
    PRIX_CHOICES = [
        (LOW, '< 300€'),
        (LOW_TO_MID, '< 450€'),
        (MID, '< 600€'),
        (MID_TO_HIGH, '< 900€'),
        (HIGH_TO_VHIGH, '< 1400€'),
        (HIGH, '< 1800€'),
    ]


    taille = models.IntegerField()
    prix = models.IntegerField(choices=PRIX_CHOICES)
    nb_chambres = models.IntegerField()
    commune = models.CharField(max_length=100)
    lien = models.CharField(max_length=300, unique=True)
    generalID = models.CharField(max_length=100)

    def dans_mes_moyens(self):
        return self.cout_par_chambre <= 600

    def cout_par_chambre(self):
        return self.prix // self.nb_chambres
    
    def cout_par_metre(self):
        return self.prix // self.taille
    
    def __str__(self):
        return str(self.prix) + '€ ' + self.commune

#allows to delete all the duplicates 'generalID' in the database. Apparently destroys all the immoweb items...
#for generalID in Appartement.objects.values_list('generalID', flat=True).distinct(): 
#   Appartement.objects.filter(pk__in=Appartement.objects.filter(generalID=generalID).values_list('id', flat=True)[1:]).delete()

polls/models.py
import datetime

from django.utils import timezone
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text

class Choice (models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

appartements/forms.py
from django import forms
from .models import Appartement

class ContactForm(forms.ModelForm):

    class Meta:
        model = Appartement
        fields = ('taille', 'prix', 'nb_chambres', 'commune', 'lien', 'generalID') 

    '''name = forms.CharField()
    email = forms.CharField(max_length=100)
    password = forms.CharField()'''

appartements/views.py
from django.shortcuts import render
from django.views import generic

from .forms import ContactForm
from .filters import AppartementFilter
from .models import Appartement

class FormView(generic.FormView):
    template_name = 'appartements/loginIndex.html'
    form_class = ContactForm


#class IndexView(generic.TemplateView):
class IndexView(generic.ListView):
    model = Appartement
    template_name = 'appartements/index.html'
    paginate_by = 15
    queryset = Appartement.objects.all().order_by('prix', '-taille')
    context_object_name = 'latest_appartements'


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        myFilter = AppartementFilter(data=self.request.GET)

        #filter is the name of the filter being called in the html
        context['filter'] = myFilter

        return context

    #the queryset above informs django the queryset to perform. This is equal to this funtion.
    #BUT this is needed here as I use the a django-filter to filter the results.
    def get_queryset(self):
        qs = self.model.objects.all().order_by('prix', '-taille')
        Appartement_filtered_list = AppartementFilter(self.request.GET, queryset=qs)

        return Appartement_filtered_list.qs


class DetailView(generic.DetailView):
    model = Appartement
    template_name = 'appartements/detail.html'

    #It looks like informating model = Appartement equals to that get_queryset function.
    #def get_queryset(self):
    #    return Appartement.objects.all()

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        '''return the last 5 published questions (not including those set to be published in the future)'''
        return Question.objects.filter(pub_date__lte = timezone.now()).order_by('pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        '''excludes any question that are not published yet'''
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question':question,
            'error_message':'You did not select a choice.',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

appartements/templates/appartements/detail.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<h1>{{ appartement }}</h1>

<ul class='list-group'>
    <li class='list-group-item'>{{ appart }}
        <ul class='list-group'>
            <li class='list-group-item'>{{ appartement.taille }} m²</li>
            <li class='list-group-item'>{{ appartement.prix }} €</li>
            <li class='list-group-item'>{{ appartement.nb_chambres }} chambre(s)</li>
            <li class='list-group-item'>{{ appartement.commune }}</li>
            <li class='list-group-item'><a href="{{appartement.lien}}">{{ appartement.lien }}</a></li>
            <li class='list-group-item'>{{ appartement.cout_par_chambre }} €/chambre</li>
            <li class='list-group-item'>{{ appartement.cout_par_metre }} €/m²</li>
            <li class='list-group-item'>ID: {{ appartement.generalID }}</li>
        </ul>
    </li>
</ul>

appartements/templates/appartements/index.html
{% load static %}

{% load my_tags %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel='stylesheet' href = '{% static "appartements/style.css" %}'>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@1,600&display=swap" rel="stylesheet"> 

    <title>Appartements</title>
  </head>
  <body>
    <form method="GET">
      {{ filter.form }}
      <button class='btn btn-primary'>
        Search
      </button>
    </form>

    <ul class='list-group'>
    {% for appartement in page_obj %}
      <li class='list-group-item'><a href="{% url 'appartements:detail' appartement.pk %}">{{ appartement }}</a></li>
    {% endfor %}
    </ul>

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="{% my_url 1 'page' request.GET.urlencode %}">&laquo; first</a>
            <a href="{% my_url page_obj.previous_page_number 'page' request.GET.urlencode %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="{% my_url page_obj.next_page_number 'page' request.GET.urlencode %}">next</a>
            <a href="{% my_url page_obj.paginator.num_pages 'page' request.GET.urlencode %}">last &raquo;</a>
        {% endif %}
    </span>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

appartements/templates/appartements/loginIndex.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V14</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'appartements/login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'appartements/login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				<form class="login100-form validate-form flex-sb flex-w">
					<span class="login100-form-title p-b-32">
						Account Login
					</span>

					<span class="txt1 p-b-11">
						Username
					</span>
					<div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
						<input class="input100" type="text" name="username" >
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
						Password
					</span>
					<div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100" type="password" name="pass" >
						<span class="focus-input100"></span>
					</div>
					
					<div class="flex-sb-m w-full p-b-48">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>

						<div>
							<a href="#" class="txt3">
								Forgot Password?
							</a>
						</div>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
				
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'appartements/login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'appartements/login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'appartements/login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'appartements/login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'appartements/login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'appartements/login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'appartements/login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'appartements/login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'appartements/login/js/main.js' %}"></script>

</body>
</html>

polls/templates/polls/detail.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href = "{% url 'polls:detail' question.id %}">Vote again?</a> 